package com.example.entity;
// Generated Feb 4, 2016 9:45:19 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Attendee generated by hbm2java
 */
@Entity
@Table(name = "attendees", catalog = "pyjioh")
public class Attendee implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private AttendeeId id;
	private Data data;

	public Attendee() {
	}

	public Attendee(AttendeeId id, Data data) {
		this.id = id;
		this.data = data;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "dataId", column = @Column(name = "data_id", nullable = false) ),
			@AttributeOverride(name = "number", column = @Column(name = "number", nullable = false) ) })
	public AttendeeId getId() {
		return this.id;
	}

	public void setId(AttendeeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "data_id", nullable = false, insertable = false, updatable = false)
	public Data getData() {
		return this.data;
	}

	public void setData(Data data) {
		this.data = data;
	}
	
}
