package main.com.example.beans;
// Generated Feb 4, 2016 3:53:42 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Attendee generated by hbm2java
 */
@Entity
@Table(name = "attendees", catalog = "pyjioh")
public class Attendee implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private AttendeeId number;
	private Data dataId;

	public Attendee() {
	}

	public Attendee(AttendeeId number, Data dataId) {
		this.number = number;
		this.dataId = dataId;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "dataId", column = @Column(name = "data_id", nullable = false) ),
			@AttributeOverride(name = "number", column = @Column(name = "number", nullable = false) ) })
	public AttendeeId getId() {
		return this.number;
	}

	public void setId(AttendeeId number) {
		this.number = number;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "data_id", nullable = false, insertable = false, updatable = false)
	public Data getData() {
		return this.dataId;
	}

	public void setData(Data data) {
		this.dataId = data;
	}

}
