package main.com.example.beans;
// Generated Feb 4, 2016 3:53:42 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AttendeeId generated by hbm2java
 */
@Embeddable
public class AttendeeId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int eventId;
	private int number;

	public AttendeeId() {
	}

	public AttendeeId(int eventId, int number) {
		this.eventId = eventId;
		this.number = number;
	}

	@Column(name = "event_id", nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@Column(name = "number", nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AttendeeId))
			return false;
		AttendeeId castOther = (AttendeeId) other;

		return (this.getEventId() == castOther.getEventId()) && (this.getNumber() == castOther.getNumber());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEventId();
		result = 37 * result + this.getNumber();
		return result;
	}

}
